services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - NODE_ENV=development
    command: npm start
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - redis
    environment:
      - NODE_ENV=test
    command: npm test
